# Generated by Django 5.2.1 on 2025-06-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('diet_type', models.IntegerField(choices=[(0, 'Vegetarian'), (1, 'Vegan'), (2, 'Pescatarian')])),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner')])),
                ('meal_category', models.IntegerField(choices=[(0, 'Appetizer'), (1, 'Main Course'), (2, 'Dessert')])),
                ('preparation_time', models.PositiveIntegerField()),
                ('cooking_time', models.PositiveIntegerField()),
                ('difficulty_level', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('number_of_servings', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement_unit', models.IntegerField(choices=[(0, 'Gram'), (1, 'Kilogram'), (2, 'Liter'), (3, 'Teaspoon'), (4, 'Tablespoon'), (5, 'Cup')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='apiapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apiapp.recipe')),
            ],
        ),
    ]
