# Generated by Django 5.2.1 on 2025-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_category',
            field=models.IntegerField(choices=[(0, 'Appetizer'), (1, 'Main course'), (2, 'Dessert')]),
        ),
    ]
