# Generated by Django 5.2.1 on 2025-10-06 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_recipe_meal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_content_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
